// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add_new_facts_array": {
            "post": {
                "description": "add facts for buffer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facts"
                ],
                "summary": "Add Facts",
                "operationId": "add-facts",
                "parameters": [
                    {
                        "description": "facts info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Facts"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    },
                    "default": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Fact": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "PeriodKey           string    ` + "`" + `json:\"period_key\"` + "`" + `\nIndicatorToMoId     int       ` + "`" + `json:\"indicator_to_mo_id\"` + "`" + `\nIndicatorToMoFactId int       ` + "`" + `json:\"indicator_to_mo_fact_id\"` + "`" + `\nValue               int       ` + "`" + `json:\"value\"` + "`" + `\nFactTime            time.Time ` + "`" + `json:\"fact_time\"` + "`" + `\nIsPlan              int       ` + "`" + `json:\"is_plan\"` + "`" + `\nAuthUserId          int       ` + "`" + `json:\"auth_user_id\"` + "`" + `",
                    "type": "string"
                },
                "period_end": {
                    "type": "string"
                },
                "period_start": {
                    "type": "string"
                }
            }
        },
        "entity.Facts": {
            "type": "object",
            "properties": {
                "facts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Fact"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Buffer",
	Description:      "API Buffer for DB",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
